* What is Hacktober Fest?
Hacktoberfest is an annual event across all of GitHub which is meant to encourage developers to contribute to open source projects. Whether it's your first step in open source or you already maintain your major project for several years, this is your oppurtunity to join us and hack for better tommorow together.

* Hacktoberfest guiding values:
- Everyone is welcome!  - Participants in Hacktoberfest represented 119 countries and thousands of skill sets (all unique). This program welcomes everyone already in the open source software community, and anyone who is interested in diving in.

- Quantity is fun, Quality is key - Participating in Hacktoberfest leads to personal growth, professional opportunities, and community building. This all starts with meaningful contributions to open source software.

- Short term action, long term impact - In the open source software community, we are standing on the shoulders of those who came before us. Your participation has a lasting effect on people and technology long after October. This is a voyage, not a race. 

* Rules:
- To get a shirt, you must make five pull requests (PRs) between October 1–31 in any timezone. 
- PRs can be to any public repo on GitHub, not just the ones highlighted.
- The PR must contain commits you made yourself (not to your own repo). 
- PRs reported by maintainers as spam or that are automated will be marked as invalid and won't count towards the shirt. 

This year, the first 50,000 of you can earn a T-shirt (compared with 30,000 in 2017). 

* Rules for contributing to this Repo
- Anybody can contribute and make PRs as long as there is no plagiarism.
- We strictly adhere to our [[https://github.com/nexussjcet/logistics/blob/master/Code%2520Of%2520Conduct.md][Code of Conduct]] and we expect everyone else in our community to do the same too.
